server:
  port: 8003

spring:
  application:
    name: stock-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:9999